#ifndef WIGNERVILLEDLL_GLOBAL_H
#define WIGNERVILLEDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WIGNERVILLEDLL_LIBRARY)
#  define WIGNERVILLEDLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WIGNERVILLEDLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WIGNERVILLEDLL_GLOBAL_H
